#To move updated Sample.txt file from local to server via github actions - Using SCP(secure copy)

#Link used for reference - https://github.com/appleboy/scp-action

#Starts from below

name: CI/CD - To replace index file input

on: [push]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY  }}
        port: ${{ secrets.PORT }}
        source: "index.html"
        target: "/var/www/pr-gtact5.vinodtestingkubeace.tk/html/index.html"  
